# Generated by Django 5.1.5 on 2025-01-27 07:06

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Byway', '0003_course'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='categories/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['svg'])]),
        ),
        migrations.AlterField(
            model_name='course',
            name='autherImg',
            field=models.FileField(blank=True, null=True, upload_to='home/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['svg'])]),
        ),
        migrations.AlterField(
            model_name='course',
            name='thumbnailImg',
            field=models.FileField(blank=True, null=True, upload_to='home/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['svg'])]),
        ),
    ]
