# Generated by Django 5.1.5 on 2025-01-27 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Byway', '0004_alter_category_image_alter_course_autherimg_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='description',
            field=models.CharField(default='No description', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='course',
            name='Title',
            field=models.CharField(default='Enter Ttitle', max_length=20),
            preserve_default=False,
        ),
    ]
