# Generated by Django 5.1.5 on 2025-01-27 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Byway', '0005_category_description_course_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='description',
            field=models.CharField(default='description', max_length=200),
            preserve_default=False,
        ),
    ]
