# Generated by Django 5.1.5 on 2025-01-27 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Byway', '0006_course_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='Title',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='course',
            name='description',
            field=models.CharField(max_length=500),
        ),
    ]
