# Generated by Django 5.1.5 on 2025-01-27 07:49

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Byway', '0007_alter_course_title_alter_course_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='thumbnailImg',
            field=models.FileField(blank=True, null=True, upload_to='home/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['svg', 'jpg', 'jpeg'])]),
        ),
    ]
